finderApp/config/routes.rb
Rails.application.routes.draw do

  resources :events do 
    resources :teams do 
      resources :members
    end 
  end
  
  devise_for :users
   # In `config/boot.rb`
   ENV['EXECJS_RUNTIME'] = 'Node'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
=begin
  get "/events", to: "events#index"
  root to: "events#index"
=end
  get "/home", to: "home#index"
  root to: "home#index"

  #get "/account", to: "home#account",  as: "account" # account_path(account)
  #get "/login", to: "home#login",  as: "login" # login_path(account)
  #get "/signup", to: "home#signup",  as: "signup" # signup_path(account)


end

finderApp/app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

finderApp/app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_team
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  # GET /members
  # GET /members.json
  def index
    @members = @team.members
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = @team.members.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json event_team_path (@team.event, @team)
  def create
    @member = @team.members.new(user_id: current_user.id)

    respond_to do |format|
      if @member.save
        format.html { redirect_to event_team_path(@team.event, @team) , notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json  

  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to event_team_path(@team.event, @team), notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = @team.members.find(params[:id])
    end
    def set_team
      @team = Team.find(params[:team_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:user_id, :team_id)
    end
end

finderApp/app/helpers/members_helper.rb
module MembersHelper
end

finderApp/app/views/members/_form.html.erb
<%= form_for[@team, @member] do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.text_field :team_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

finderApp/app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', edit_event_team_member_path (@event, @team,@member) %> |
<%= link_to 'Back', event_team_members_path (@team) %>

finderApp/app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.user %></td>
        <td><%= member.team %></td>
        <td><%= link_to 'Show', event_team_member_path (@team , member) %></td>
        <td><%= link_to 'Edit', edit_event_team_member_path(@team , member) %></td>
        <td><%= link_to 'Destroy', event_team_member_path (@team , member), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_event_team_member_path(@member) %>
<%= link_to 'Back', event_team_path(@team) %>

finderApp/app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', event_team_members_path (@team) %>

finderApp/app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @member.user %>
</p>

<p>
  <strong>Team:</strong>
  <%= @member.team %>
</p>

<%= link_to 'Edit', edit_event_team_member_path(@team , @member) %> |
<%= link_to 'Back', event_team_members_path(@team) %>