finderApp/config/routes.rb
Rails.application.routes.draw do

  resources :events do 
    resources :teams do 
      resources :members
    end 
  end
  
  devise_for :users
   # In `config/boot.rb`
   ENV['EXECJS_RUNTIME'] = 'Node'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
=begin
  get "/events", to: "events#index"
  root to: "events#index"
=end
  get "/home", to: "home#index"
  root to: "home#index"

  #get "/account", to: "home#account",  as: "account" # account_path(account)
  #get "/login", to: "home#login",  as: "login" # login_path(account)
  #get "/signup", to: "home#signup",  as: "signup" # signup_path(account)


end

finderApp/app/models/event.rb
class Event < ApplicationRecord
    belongs_to :user 
    has_many :teams

    validates :nameEvent, :date, :time , presence: true 

    validates_length_of :nameEvent, minimum: 10 , maximum: 50
    validates_length_of :description , maximum: 300
    validates_length_of :duration , maximum: 30
    validates_length_of :location,  minimum: 10 , maximum: 30



end

finderApp/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    #Event.all      current_user.events
    @events = current_user.events
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = current_user.events.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.new(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:nameEvent, :description, :date, :time, :duration, :team, :location)
    end
end

finderApp/app/helpers/events_helper.rb
module EventsHelper
end

finderApp/app/views/events/_form.html.erb
<div class="form-container col-12 col-md-8">
<section class="">
  <%= form_with(model: event, local: true) do |form| %>
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :Event_Name %>
      <%= form.text_field :nameEvent ,class:"form-control"  %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_field :description, class:"form-control"%>
    </div>

    <div class="field">
      <%= form.label :date %>
      <%= form.date_select :date %>
    </div>

    <div class="field">
      <%= form.label :time %>
      <%= form.time_select :time %>
    </div>

    <div class="field">
      <%= form.label :duration %>
      <%= form.text_field :duration ,class:"form-control"  %>
    </div>

    <div class="field">
      <%= form.label :team %>
      <%= form.text_field :team,class:"form-control"  %>
    </div>

    <div class="field">
      <%= form.label :location %>
      <%= form.text_field :location,class:"form-control"  %>
    </div>

    
    <div class="actions">
      <%= form.submit "Submit", class:"btn btn-primary" %>      
    </div>
  <% end %>
</div>
</div>

finderApp/app/views/events/edit.html.erb
<h1>Editing Event</h1>
<% if user_signed_in? %>
    <%= render 'form', event: @event %>
    <br>
    <%= link_to 'Show', @event , class:"btn-primary show_btn_postion" %> 
    <%= link_to 'Back', events_path, class:"btn-primary back_btn_postion" %>
<% else %>

    <p>you have to logged in </p>
    <%= link_to 'Back', event_path, class:"btn-primary" %>
    <%= link_to "Sign Up", new_user_registration_path, class:"bbtn-primary" %>
    <%= link_to "Sing in", new_user_session_path, class:"btn-primary" %>
<% end %>

finderApp/app/views/events/index.html.erb
<main class="container">
    <p id="notice"><%= notice %></p>

    <h1 class="section_title page_name">Events</h1>

    <%= link_to 'New Event', new_event_path, class:"btn btn-primary btn_postion" %>

    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Name event</th>
          <th scope="col">Description</th>
          <th scope="col">Date</th>
          <th scope="col">Location</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td><%= event.nameEvent %></td>
            <td><%= event.description %></td>
            <td><%= event.date %></td>
            <td><%= event.location %></td>
            <td><%= link_to event do %>
              <%=  image_tag ('icon_show.png' ), class:"icon" %>
            <% end %></td>
            <td><%= link_to edit_event_path(event) do %>
              <%=  image_tag ('icon_edit.png' ), class:"icon" %>
            <% end %></td>
            <td><%= link_to  event, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <%=  image_tag ('icon_delete.png' ), class:"icon" %>
            <% end %></td>

          </tr>
        <% end %>
      </tbody>
    </table>

</main>

finderApp/app/views/events/new.html.erb
<h1 class="section_title page_name2">New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'cancel', events_path,  class:"btn btn-primary fix_btn" %>

finderApp/app/views/events/show.html.erb
<section class="show_margin">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Event Name:</strong>
      <%= @event.nameEvent %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @event.description %>
    </p>

    <p>
      <strong>Date:</strong>
      <%= @event.date %>
    </p>

    <p>
      <strong>Time:</strong>
      <%= @event.time %>
    </p>

    <p>
      <strong>Duration:</strong>
      <%= @event.duration %>
    </p>

    <p>
      <strong>Team:</strong>
      <%= @event.team %>
    </p>

    <p>
      <strong>Location:</strong>
      <%= @event.location %>
    </p>
</section>
<br>
<section class="margin-btn">
    <% if user_signed_in? %>
      <% if @event.user_id == current_user.id  %>
        <%= link_to 'Edit', edit_event_path(@event),class:"btn btn-primary" %> 
      <% end %>
      <%= link_to 'Create Team', new_event_team_path(@event),class:"btn btn-primary" %> 
      <%= link_to 'Join to Team', event_teams_path(@event),class:"btn btn-primary" %> 
      <%= link_to 'Back', home_path, class:"btn btn-primary" %>

    <% else %>
      <%= link_to 'Back', home_path ,class:"btn btn-primary"%>
      
    <% end %>
</section>

 